services:
  nginx:
    ports:
      - "${SGE_HTTP_PORT:-8080}:8080"
      - "8443:8443"

  sqlserver:
    ports:
      - "${SGE_SQLSERVER_PORT:-1433}:1433"

  redis:
    ports:
      - "${SGE_REDIS_PORT:-6379}:6379"

  rabbitmq:
    ports:
      - "${SGE_RABBITMQ_MANAGEMENT_PORT:-15672}:15672"

  otel-collector:
    ports:
      - "${SGE_OTLP_GRPC_PORT:-4317}:4317"
      - "${SGE_OTLP_HTTP_PORT:-4318}:4318"
