services:
  api:
    environment:
      DOTNET_ENVIRONMENT: Development

  worker:
    environment:
      DOTNET_ENVIRONMENT: Development

  nginx:
    environment:
      NGINX_GENERATE_SELF_SIGNED_CERTIFICATE: "true"
    ports:
      - "127.0.0.1:${SGE_HTTP_PORT:-8080}:8080"
      - "127.0.0.1:${SGE_HTTPS_PORT:-8443}:8443"
